{
 "title": "Jira",
 "description": "Shows Jira JVM and usage metrics",
 "tags": [
  "prometheus",
  "Atlassian"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Staled Issues Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "staled_issues_count", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"jira\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"jira\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{job=\"jira\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"jira\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=\"jira\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "JIRA Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Update Issues Per Project",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jira_issue_update_count) by (projectKey)",
     "legendFormat": "{{projectKey}}"
    }
   ]
  },
  {
   "title": "Update Issues Per User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jira_issue_update_count) by (username)",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Login/Logout",
   "type": "graph",
   "description": "Login/Logout increases per 1 hour",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jira_user_login_count[1h]))",
     "legendFormat": "Login"
    },
    {
     "expr": "sum(increase(jira_user_logout_count[1h]))",
     "legendFormat": "Logout"
    }
   ]
  },
  {
   "title": "Dashboards Views",
   "type": "graph",
   "description": "Views of all dashboards increases",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jira_dashboard_view_count[1h]))"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(jira_request_duration_on_path_sum[1m])) by (path)) / (sum(rate(jira_request_duration_on_path_count[1m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Common Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Attachments",
   "type": "singlestat",
   "description": "Displays the current attachments size",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "jira_total_attachment_size_gauge"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "The uptime of the Java virtual machine in milliseconds",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "jvm_uptime_gauge" }
   ]
  },
  {
   "title": "Total Issues",
   "type": "singlestat",
   "description": "The total issues in JIRA",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_total_issues_gauge" }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "All Users",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_all_users_gauge" }
   ]
  },
  {
   "title": "Active Users",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_active_users_gauge " }
   ]
  },
  {
   "title": "Total Sessions",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_total_sessions_gauge" }
   ]
  },
  {
   "title": "Authorized  Sessions",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_authorized_sessions_gauge" }
   ]
  }
 ]
}